### ISSUE TITLE
[BUG] Liveliness/readiness probes not working

### ISSUE THREAD

**Issue by rverma-nikiai** [aws/aws-app-mesh-examples#137]
**Describe the bug**
While using the app mesh if a pod have liveliness/readiness probes it failed since the probes are configured on pod IP. 

**Platform**
EKS

**To Reproduce**
Create a pod with liveliness and readiness probe enabled.
Deploy appmesh-inject and appmesh-system
Recreate pod to observe health check failed and the pod doesn't come up

**Expected behavior**
A way to use liveliness/readiness probe

**Additional context**
A bonus would be appmesh controller can configure health check on virtual nodes automatically by reading the deployment definition.

**Comment by kiranmeduri** [comment]
I believe this is because Envoy is not primed yet with the configuration from App Mesh. By default Envoy is configured to drop all traffic and based on the configuration provided for VirtualNode it will receive configuration to allow traffic to specific backends. In this case you may have a case of aggressive probes. Can you share the configuration used for readiness and liveness probe so that we can reproduce? I tried with the following and was able to get it to work.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: colorteller-black
  namespace: ${APP_NAMESPACE}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: colorteller
      version: black
  template:
    metadata:
      annotations:
        appmesh.k8s.aws/mesh: ${MESH_NAME}
      labels:
        app: colorteller
        version: black
    spec:
      containers:
        - name: colorteller
          image: ${COLOR_TELLER_IMAGE}
          livenessProbe:
            httpGet:
              port: 9080
              path: /
          readinessProbe:
            httpGet:
              port: 9080
              path: /
          ports:
            - containerPort: 9080
          env:
            - name: "SERVER_PORT"
              value: "9080"
            - name: "COLOR"
              value: "black"
```
