### ISSUE TITLE
Question: X-Ray sidecar with Fargate

### ISSUE THREAD

**Issue by uhef** [aws/aws-app-mesh-examples#141]
I've followed the instructions in colorapp example to take App Mesh and X-Ray into use in our existing service running on Fargate. Everything seems fine otherwise but we cannot get any data in to X-Ray. When looking at the x-ray container logs it might be that we have found the culprit:
```
[Error] Get instance id metadata failed: RequestError: send request failed
caused by: Get http://169.254.169.254/latest/meta-data/instance-id: dial tcp 169.254.169.254:80: connect: invalid argument
```
It seems that the x-ray container tries to get instance metadata but cannot. I wonder if this is because we are running the service in Fargate and not ECS.

**Comment by uhef** [comment]
Some update on this. Apparently this error can safely be ignored. For more information see this:

https://forums.aws.amazon.com/thread.jspa?messageID=857509&#857509

I modified the container entrypoint so that the x-ray daemon is ran in local-mode:

```
{
            "name": "xray-daemon",
            "image": "amazon/aws-xray-daemon",
            "entryPoint": ["/usr/bin/xray", "-b", "0.0.0.0:2000", "-o"],
            "user": "1337",
            "essential": true,
            "cpu": 32,
            "memoryReservation": 256,
            "portMappings": [
                {
                "hostPort": 2000,
                "containerPort": 2000,
                "protocol": "udp"
                }
            ],
            "logConfiguration": {
                "logDriver": "awslogs",
                "options": {
                    "awslogs-group": "...",
                    "awslogs-region": "...",
                    "awslogs-stream-prefix": "..."
                }
            }
        }
```

This will rid us of the error but the problem still persist. We get no data to X-Ray.

**Comment by bcelenza** [comment]
@uhef So you're saying that you still aren't receiving data in X-Ray? Do you get any different errors in your X-Ray container after the initial issue with instance metadata?

**Comment by kiranmeduri** [comment]
I am able to get x-ray traces in **Fargate** using the following container-definition. Can you please confirm if you are still not seeing X-Ray data.

```
  - Name: "xray-daemon"
    Image: "amazon/aws-xray-daemon"
    User: "1337"
    Essential: true
    Cpu: 32
    MemoryReservation: 256
    PortMappings:
    - ContainerPort: 2000
        Protocol: "udp"
    LogConfiguration:
    LogDriver: "awslogs"
    Options:
        awslogs-group:
        'Fn::ImportValue': !Sub "${EnvironmentName}:ECSServiceLogGroup"
        awslogs-region: { Ref: "AWS::Region" }
        awslogs-stream-prefix: "colorteller-red-xray-daemon"
```

![Screen Shot 2019-06-05 at 9 31 26 AM](https://user-images.githubusercontent.com/4035/58973418-c86c2f00-8774-11e9-8006-5be4d7366aa6.png)
