### ISSUE TITLE
[BUG] Deloy service to ECS stuck at PRE_INITIALIZING state

### ISSUE THREAD

**Issue by myyee** [aws/aws-app-mesh-examples#173]
**Describe the bug**
Gateway and ColorTeller services stuck in PENDING state. Envoy won't become healthy because it is stuck at the PRE_INITIALIZING state.

**Platform**
ECS

**To Reproduce**
Follow the instructions in the [colorapp README](https://github.com/aws/aws-app-mesh-examples/blob/master/examples/apps/colorapp/README.md) until step "Deploy services to ECS"

**Expected behavior**
Gateway and ColorTeller services in RUNNING state.

**Config files, and API responses**
*server_info*
```
 bash-4.2$ curl http://localhost:9901/server_info
{
 "version": "ae8c8aa036e58e39b3d2fba81f5bdc4683a30682/1.9.0/Clean/DEBUG/BoringSSL",
 "state": "PRE_INITIALIZING",
 "command_line_options": {
  "base_id": "0",
  "concurrency": 2,
  "config_path": "/tmp/envoy.yaml",
  "config_yaml": "",
  "allow_unknown_fields": false,
  "admin_address_path": "",
  "local_address_ip_version": "v4",
  "log_level": "debug",
  "component_log_level": "",
  "log_format": "[%Y-%m-%d %T.%e][%t][%l][%n] %v",
  "log_path": "",
  "hot_restart_version": false,
  "service_cluster": "",
  "service_node": "",
  "service_zone": "",
  "mode": "Serve",
  "max_stats": "16384",
  "max_obj_name_len": "500",
  "disable_hot_restart": false,
  "enable_mutex_tracing": false,
  "restart_epoch": 0,
  "file_flush_interval": "10s",
  "drain_time": "600s",
  "parent_shutdown_time": "900s"
 },
 "uptime_current_epoch": "3046s",
 "uptime_all_epochs": "3046s"
}
```

*envoy.yml*
```
bash-4.2$ cat /tmp/envoy.yaml
admin:
  access_log_path: /tmp/envoy_admin_access.log
  # Provides access to: http://<envoy hostname>:9901/config_dump
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

node:
    id: mesh/appmesh-mesh/virtualNode/colorteller-black-vn
    cluster: mesh/appmesh-mesh/virtualNode/colorteller-black-vn

dynamic_resources:
  # Configure Envoy to get listeners and clusters via GRPC ADS
  ads_config:
    api_type: GRPC
    grpc_services:
      google_grpc:
        target_uri: appmesh-envoy-management.us-west-2.amazonaws.com:443
        stat_prefix: ads
        channel_credentials:
          ssl_credentials:
            root_certs:
              filename: /etc/pki/tls/cert.pem
        credentials_factory_name: envoy.grpc_credentials.aws_iam
        call_credentials:
          from_plugin:
            name: envoy.grpc_credentials.aws_iam
            config:
              region: us-west-2
              service_name: appmesh
  lds_config: {ads: {}}
  cds_config: {ads: {}}


tracing:
  http:
    name: envoy.xray
    config:
      daemon_endpoint: "127.0.0.1:2000"

stats_config:
  stats_tags:
    - tag_name: "appmesh.mesh"
      fixed_value: "appmesh-mesh"
    - tag_name: "appmesh.virtual_node"
      fixed_value: "colorteller-black-vn"
```

**Additional context**
Tested in us-west-2 and us-east-1 region.

**Comment by lavignes** [comment]
@myyee I see you resolved this issue. I'm curious if / how you resolved it. If there is something we could improve on in our examples or documentation that would prevent others from getting similarly stuck, we'd love to know.

**Comment by myyee** [comment]
I totally missed the "Configure App Mesh resources" step twice. When I scroll through the page, I was looking for deploy keyword as the main section title is "Deploy the application". A screenshot showing the virtual nodes in the "create mesh resources" and another screenshot showing the ECS services in the "Deploy services to ECS" will be helpful. Also, adding step number can be helpful too. 

I'm still stuck at the PRE_INITIALIZING state for my own project. It seems like APPMESH_VIRTUAL_NODE_NAME is the bare mininum that I need to set for the envoy instance based on the AWS documentation. Am I missing something?

**Comment by kobayashilin** [comment]
> I totally missed the "Configure App Mesh resources" step twice. When I scroll through the page, I was looking for deploy keyword as the main section title is "Deploy the application". A screenshot showing the virtual nodes in the "create mesh resources" and another screenshot showing the ECS services in the "Deploy services to ECS" will be helpful. Also, adding step number can be helpful too.
> 
> I'm still stuck at the PRE_INITIALIZING state for my own project. It seems like APPMESH_VIRTUAL_NODE_NAME is the bare mininum that I need to set for the envoy instance based on the AWS documentation. Am I missing something?

I encountered similar issue.
Is it possible that be a network issue (e.g., proxy) ?
When I curl target_uri which in tmp/envoy.yaml, it encountered connection timeout.

The message below:
```
bash-4.2$ cat tmp/envoy.yaml
admin:
  access_log_path: /tmp/envoy_admin_access.log
  # Provides access to: http://<envoy hostname>:9901/config_dump
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

node:
    id: mesh/yt-mesh-local/virtualNode/yt-mesh-BLABLA
    cluster: mesh/yt-mesh-local/virtualNode/yt-mesh-BLABLA

dynamic_resources:
  # Configure Envoy to get listeners and clusters via GRPC ADS
  ads_config:
    api_type: GRPC
    grpc_services:
      google_grpc:
        target_uri: appmesh-envoy-management.ap-southeast-1.amazonaws.com:443
        stat_prefix: ads
        channel_credentials:
          ssl_credentials:
            root_certs:
              filename: /etc/pki/tls/cert.pem
        credentials_factory_name: envoy.grpc_credentials.aws_iam
        call_credentials:
          from_plugin:
            name: envoy.grpc_credentials.aws_iam
            config:
              region: ap-southeast-1
              service_name: appmesh
  lds_config: {ads: {}}
  cds_config: {ads: {}}

bash-4.2$ curl https://appmesh-envoy-management.ap-southeast-1.amazonaws.com
curl: (7) Failed to connect to appmesh-envoy-management.ap-southeast-1.amazonaws.com port 443: Connection timed out
```

However, it can get response from outside ecs host.
