### ISSUE TITLE
[BUG] can't add 4 virtual nodes in examples/apps/colorapp/servicemesh/appmesh-colorapp.yaml

### ISSUE THREAD

**Issue by ozbillwang** [aws/aws-app-mesh-examples#175]
Tasks

Edit https://github.com/aws/aws-app-mesh-examples/blob/master/examples/apps/colorapp/servicemesh/appmesh-colorapp.yaml#L126-L132 add additional black virtual node. So totally have 4

```
  ColorTellerRoute:
    Type: AWS::AppMesh::Route
    DependsOn:
      - ColorTellerVirtualRouter
      - ColorTellerWhiteVirtualNode
      - ColorTellerRedVirtualNode
      - ColorTellerBlueVirtualNode
    Properties:
      MeshName: !Ref AppMeshMeshName
      VirtualRouterName: colorteller-vr
      RouteName: colorteller-route
      Spec:
        HttpRoute:
          Action:
            WeightedTargets:
              - VirtualNode: colorteller-white-vn
                Weight: 1
              - VirtualNode: colorteller-blue-vn
                Weight: 1
              - VirtualNode: colorteller-red-vn
                Weight: 1
              - VirtualNode: colorteller-black-vn
                Weight: 1
          Match:
            Prefix: "/"
```

**Describe the bug**

>Property validation failure: [Number of items for property {/Spec/HttpRoute/Action/WeightedTargets} is greater than maximum allowed items {3}]

**Platform**
ECS

**To Reproduce**

Described above

**Expected behavior**

It is fine, when manually add new virtual nodes in aws console,  but can't deploy via cloudformation.
