### ISSUE TITLE
[BUG] aws-appmesh-envoy not pulling X-Ray sampling rules from managed service

### ISSUE THREAD

**Issue by myyee** [aws/aws-app-mesh-examples#195]
**Describe the bug**
It looks like the aws-appmesh-envoy container is having difficulty pulling sampling rules from the managed X-Ray service. I have added my custom sampling rules to the X-Ray but it's not working. I'm seeing these in the log

```
[2019-08-19 14:55:03.045][000023][info][tracing] [source/extensions/tracers/xray/sampling.cc:114] unable to parse empty json file. falling back to default rule set.
[2019-08-19 14:55:03.045][000024][info][tracing] [source/extensions/tracers/xray/sampling.cc:114] unable to parse empty json file. falling back to default rule set.
```
**Platform**
ECS

**To Reproduce**
Set ENABLE_ENVOY_XRAY_TRACING environment variable to 1 for the aws-appmesh-envoy container

**Expected behavior**
Some other or none of the above messages in the log

**Config files, and API responses**
task-definition
```
    {
        "name": "envoy",
        "image": "111345817488.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-envoy:v1.9.1.0-prod",
        "cpu": 64,
        "memory": 128,
        "memoryReservation": 64,
        "portMappings": [
            {
                "protocol": "tcp",
                "containerPort": 9901
            },
            {
                "protocol": "tcp",
                "containerPort": 15000
            },
            {
                "protocol": "tcp",
                "containerPort": 15001
            }
        ],
        "essential": true,
        "environment": [
            {
                "name": "APPMESH_VIRTUAL_NODE_NAME",
                "value": "mesh/appmesh/virtualNode/service1-node"
            },
            {
                "name": "ENABLE_ENVOY_XRAY_TRACING",
                "value": "1"
            }
        ],
        "healthCheck": {
            "command": [
                "CMD-SHELL",
                "curl -s http://localhost:9901/server_info | grep state | grep -q LIVE"
            ],
            "interval": 5,
            "timeout": 2,
            "retries": 3
        },
        "user": "1337",
        "logConfiguration": {
            "logDriver": "awslogs",
            "options": {
                "awslogs-group": "/appmesh/service1/envoy",
                "awslogs-region": "us-west-2"
            }
        }
    }
```

**Comment by lavignes** [comment]
@myyee Did you perhaps [miss the step on adding the xray daemon](https://docs.aws.amazon.com/xray/latest/devguide/xray-services-appmesh.html) in your task definition?

https://docs.aws.amazon.com/xray/latest/devguide/xray-daemon-ecs.html

**Comment by lavignes** [comment]
You can add something this to your task definition:

```
      - Name: xray
        Image: 'amazon/aws-xray-daemon'
        Essential: true
        User: '1337'
        Cpu: 32
        MemoryReservation: 256
        PortMappings:
        - ContainerPort: 2000
          Protocol: 'udp'
        LogConfiguration:
          LogDriver: 'awslogs'
          Options:
            awslogs-group: 'myapp-log-group'
            awslogs-region: !Ref AWS::Region
            awslogs-stream-prefix: 'myapp-xray'
```

And add the `arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess` policy to your Task's IAM role:

```
  TaskIamRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument: |
        {
            "Statement": [{
                "Effect": "Allow",
                "Principal": { "Service": [ "ecs-tasks.amazonaws.com" ]},
                "Action": [ "sts:AssumeRole" ]
            }]
        }
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/CloudWatchFullAccess
      - arn:aws:iam::aws:policy/AWSAppMeshEnvoyAccess
      - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
```
