### ISSUE TITLE
[BUG] virtual route "color-route" failed to be updated with retry policy

### ISSUE THREAD

**Issue by XiaoYangZhu** [aws/aws-app-mesh-examples#233]
_**Important note on security disclosures**: If you think you’ve found a potential security issue, please do not post it in the Issues.  Instead, please follow the instructions [here](https://aws.amazon.com/security/vulnerability-reporting/) or [email AWS security directly](mailto:aws-security@amazon.com)._

**Describe the bug**
When going through the case of "aws-app-mesh-examples/walkthroughs/howto-k8s-retry-policy/", it was noticed that the virtual route "color-route" of mesh "howto-k8s-retry-policy" was not refreshed with retry policy uncommented in the file "manifest.yaml.template".

**Platform**
EKS 1.14

**To Reproduce**
1. execute "./deploy.sh" under foler ".../walkthroughs/howto-k8s-retry-policy"

2. the service mesh was successfully provisioned based on the content of file "manifest.yaml.template", where the retry policy below is commented as:

![image](https://user-images.githubusercontent.com/24489117/69481489-c3975680-0e4c-11ea-852b-c1fa84309b09.png)

3. then update the file "manifest.yaml.template" and uncomment the section mentioned in step-2 above, and then execute "./deploy.sh" again, we can see the generated file "_output/manifest.yaml" was generated as expected:

![image](https://user-images.githubusercontent.com/24489117/69481598-a747e980-0e4d-11ea-8ac6-8b1e40449e50.png)

4. check the virtual service "color.howto-k8s-retry-policy.svc.cluster.local" and we can also see it was successfully updated as below:

![image](https://user-images.githubusercontent.com/24489117/69481557-533d0500-0e4d-11ea-82ab-b36a71e88cdb.png)

5. however, when checking the virtual route "color-route" in the console, we can see it was not updated with the retry policy as expected as below:

![image](https://user-images.githubusercontent.com/24489117/69481627-deb69600-0e4d-11ea-8372-e8431c7bab81.png)

**Expected behavior**
The virtual route "color-route" should be reconfigured successfully with the updated retry poilcy.

**Config files, and API responses**
If applicable config files and responses from our API.

**Additional context**

**Comment by efe-selcuk** [comment]
It looks like you have an indentation issue. `retryPolicy` should be at the same indentation as `action`, not nested under it. I'm not familiar with how k8s processes CRDs but I'm guessing it will accept unknown fields but ignore them.

```
  routes:
    - name: color-route
      http:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeName: blue
              weight: 1
        # UNCOMMENT below to enable retries
        retryPolicy:
          maxRetries: 4
          perRetryTimeoutMillis: 2000
          httpRetryEvents:
            - server-error
```

```
Spec:
  Mesh Name:  howto-k8s-retry-policy
  Routes:
    Http:
      Action:
        Weighted Targets:
          Virtual Node Name:  blue
          Weight:             1
      Match:
        Prefix:  /
      Retry Policy:
        Http Retry Events:
          server-error
        Max Retries:               4
        Per Retry Timeout Millis:  2000
    Name: color-route
```

I just ran through the example myself and I'm able to see the retry policy effected.
