### ISSUE TITLE
Q: Encrypting LB to service traffic

### ISSUE THREAD

**Issue by adanilinel1** [aws/aws-app-mesh-examples#276]
I've noticed that while the traffic between the VitualNodes is encrypted by App Mesh, ALB still connects to the service using HTTP protocol (target group health check, etc)
Is there any way to also implement TLS encryption though envoy for the load balancer connections?

**Comment by bcelenza** [comment]
Hey @adanilinel1, I take it you mean encrypting traffic from the load balancer on the [TLS walkthrough](https://github.com/aws/aws-app-mesh-examples/tree/master/walkthroughs/tls-with-acm) (and in general)??

This is doable. The short answer:

1. Enable TLS termination on the virtual node behind the load balancer the same way as done in the walkthrough (mode: STRICT, using a certificate of your choosing).
2. In the [routing configuration](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-target-groups.html) for your load balancer target groups, specify HTTPS and the port of the virtual node behind the load balancer.

The walkthrough can be updated to incorporate this as well — we kept it simple to start, but it feels like a miss now that we aren’t demonstrating encryption from the ALB.

**Comment by adanilinel1** [comment]
> Hey @adanilinel1, I take it you mean encrypting traffic from the load balancer on the [TLS walkthrough](https://github.com/aws/aws-app-mesh-examples/tree/master/walkthroughs/tls-with-acm) (and in general)?
> 
> This is doable. The short answer:
> 
> 1. Enable TLS termination on the virtual node behind the load balancer the same way as done in the walkthrough (mode: STRICT, using a certificate of your choosing).
> 2. In the [routing configuration](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-target-groups.html) for your load balancer target groups, specify HTTPS and the port of the virtual node behind the load balancer.
> 
> The walkthrough can be updated to incorporate this as well — we kept it simple to start, but it feels like a miss now that we aren’t demonstrating encryption from the ALB.

Thanks for the response! I did just that based on your walkthrough, however the target group HTTPS health check fails
```
VirtualNode:
  ...
          Listeners:
          - PortMapping:
              Port: 8080
              Protocol: http
            HealthCheck:
              Protocol: http
              Path: /health
              HealthyThreshold: 2
              UnhealthyThreshold: 2
              TimeoutMillis: 2000
              IntervalMillis: 5000
            TLS:
              Mode: STRICT
              Certificate:
                ACM:
                  CertificateArn: !Ref CertificateARN

ECSTask:
  - service container:
          PortMappings:
            - ContainerPort: 8080
               Protocol: tcp
  - envoy container:
          PortMappings:
            - ContainerPort: 9901
              Protocol: 'tcp'
            - ContainerPort: 15000
              Protocol: 'tcp'
            - ContainerPort: 15001
              Protocol: 'tcp'
      ProxyConfiguration:
        Type: 'APPMESH'
        ContainerName: 'envoy'
        ProxyConfigurationProperties:
          - Name: 'IgnoredUID'
            Value: '1337'
          - Name: 'ProxyIngressPort'
            Value: '15000'
          - Name: 'ProxyEgressPort'
            Value: '15001'
          - Name: 'AppPorts'
            Value: '8080'
          - Name: 'EgressIgnoredIPs'
            Value: '169.254.170.2,169.254.169.254,52.94.0.0/22,52.119.224.0/20'

  Service:
      LaunchType: FARGATE
      LoadBalancers:
        - TargetGroupArn: !Ref NLBTargetGroup
          ContainerPort: 8080
          ContainerName: service

  NLBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath:
        Fn::Sub: /health
      HealthCheckProtocol: HTTPS
      HealthyThresholdCount: 2
      Port: 8080
      Protocol: TCP
      TargetType: ip
      UnhealthyThresholdCount: 2
      VpcId: !Ref VpcId
 ```
Everything starts, but NLB target group health check fails, and the ECS task is restarted

**Comment by adanilinel1** [comment]
Not sure if I understood your instructions above correctly.
Using the walkthrough as a base, I modified the target group to use HTTPS:
```
  WebTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 6
      HealthCheckPath: /ping
      HealthCheckProtocol: HTTPS
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      TargetType: ip
      Name: !Sub "${EnvironmentName}-web"
      Port: 80
      Protocol: HTTPS
      UnhealthyThresholdCount: 2
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: "120"
      VpcId:
        'Fn::ImportValue': !Sub "${EnvironmentName}:VPC"
```
After re-deploying with this change, the gateway task started to fail ELB health check and was terminated
