### ISSUE TITLE
[BUG] Can not remove the ending / in k8s manifest

### ISSUE THREAD

**Issue by chuongnguyen5397** [aws/aws-app-mesh-examples#520]
**Describe the bug**
I'm using Kubernetes manifest to create Gateway Route
```
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: GatewayRoute
metadata:
  name: service
  namespace: develop
spec:
  awsName: service
  httpRoute:
    match:
      prefix: /api/service/
      port: 80
    action:
      rewrite:
        prefix:
          defaultPrefix: DISABLED
      target:
        virtualService:
          virtualServiceRef:
            name: service
```

I want to remove the ending `/` at prefix `/api/service/` in the manifest file but the CRDs does not allow me to do it. But I can remove it on Console but it keeps adding the `/` again.

Does anyone know how to get through this one?

**Platform**
EKS

**Expected behavior**

**Config files, and API responses**
Here is the CRDs file that I'm using: kubectl apply -k "https://github.com/aws/eks-charts/stable/appmesh-controller/crds?ref=master"

**Comment by BennettJames** [comment]
Hello,

I'm having trouble replicating the behavior. Can you please provide the following:

- the version of the controller you have installed
- the exact manifest file you are using
- the output data that is incorrect

**Comment by chuongnguyen5397** [comment]
Hi, 

The controller's version is: appmesh-controller:v1.9.0

My manifest file to create Gateway Route:

```
apiVersion: appmesh.k8s.aws/v1beta2
kind: GatewayRoute
metadata:
  name: backend-service
  namespace: develop
  labels:
    gateway: ingress-gw
spec:
  awsName:backend-service
  httpRoute:
    match:
      prefix: /api/backend
      port: 8088
    action:
      rewrite:
        prefix:
          defaultPrefix: DISABLED
      target:
        virtualService:
          virtualServiceRef:
            name: backend-service
```

The error I got is here:

```
Error from server (Prefix to be matched on must start and end with '/'): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"appmesh.k8s.aws/v1beta2\",.......
```

So what I have done to get through it here by created it manually in the console, and it worked without the `/`
